---

- name: NFS server configuration
  hosts: ansible
  gather_facts: false

  tasks:

  - name: Make directory /data/nfs
    file:
      path: /data/nfs
      state: directory

  - name: Open service nfs in Firewall
    firewalld:
      service: nfs
      source: 10.0.2.0/24
      permanent: yes
      state: enabled

  - name: install the latest version of nfs-utils
    dnf:
      name: nfs-utils
      state: latest

  - name: enable nfs-utils
    command: systemctl enable --now nfs-server
  - name: enable rpcbind
    command: systemctl enable --now rpcbind

  - name: configure /etc/hosts
    command: echo '10.0.2.95 nfs-server' >> /etc/hosts

  - name: configure /etc/fstab
    command: echo 'nfs-server:/data/nfs  /data/nfsshare   nfs defaults   0 0' >> /etc/fstab

  - name: configure /etc/exports
    command: echo '/data/nfs 10.0.2.0/24(rw,sync,no_root_squash)' >> /etc/exports

  - name: restart nfs-utils
    command: systemctl restart nfs-server
  - name: enable rpcbind
    command: systemctl restart rpcbind
