
## Change settings to your specification

# hosts
# ansible.cfg
# vars.yml

---

- name: Main settings
  hosts: debian
  ignore_unreachable: true
  gather_facts: false
  ignore_errors: yes
  check_mode: no #  (full/yes = dryrun!)
  vars_files:
    - vars.yml

  tasks:

  - include_tasks: network.yml
  - include_tasks: time.yml
  - include_tasks: logrotate.yml
  - include_tasks: users.yml
  - include_tasks: iptables.yml
  - include_tasks: swap.yml
  - include_tasks: packages.yml
  - include_tasks: kvm.yml
  - include_tasks: cockpit.yml
