
## Change settings to your specification

---

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes

- name: Install Basic packages
  ansible.builtin.apt:
    name:
    - fdisk
    - htop
    - lshw
    - nmap
    - neofetch
    - parted
    - plocate
    - sysfsutils
    - tree
    state: latest
    update_cache: yes
    install_recommends: no

